%%%
% @author Alex Badan
% @date 29/06/2017
% @package test
%
% Simple script to add all packages to matlab path
%%%

addpath( ...
  './calibration/', ...
  './coordinates/', ...
  './evaluation/', ...
  './examples/', ...
  './fex/', ...
  './filters/', ...
  './gui/', ...
  './math/', ...
  './signals/', ...
  './subfilters/', ...
  './tools/', ...
  './wpms/' ...
);
